FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock /app/
COPY frontend/package.json /app/frontend/package.json

WORKDIR /app/frontend

RUN bun install

COPY ./frontend /app/frontend

CMD ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "5173"]
