"""add purchase_record logical delete fields

Revision ID: 301f7147f297
Revises: e577414cbebe
Create Date: 2026-04-19 21:00:21.784115

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '301f7147f297'
down_revision = 'e577414cbebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_record', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('purchase_record', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_record', 'deleted_at')
    op.drop_column('purchase_record', 'is_deleted')
    # ### end Alembic commands ###
