"""add amount to item

Revision ID: 8bf59a1e7457
Revises: d6c6487f85a5
Create Date: 2026-04-11 18:12:10.836744

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8bf59a1e7457'
down_revision = 'd6c6487f85a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
