"""TEST

Revision ID: d6c6487f85a5
Revises: fe56fa70289e
Create Date: 2026-04-11 17:29:36.696490

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6c6487f85a5'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('test_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'test_amount')
    op.drop_column('item', 'amount')
    # ### end Alembic commands ###
