/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRecycleBinRouteImport } from './routes/_layout/recycle-bin'
import { Route as LayoutPurchaseRecordSummaryRouteImport } from './routes/_layout/purchase-record-summary'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutExpenseSubcategoryRouteImport } from './routes/_layout/expense-subcategory'
import { Route as LayoutExpenseCategoryRouteImport } from './routes/_layout/expense-category'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecycleBinRoute = LayoutRecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPurchaseRecordSummaryRoute =
  LayoutPurchaseRecordSummaryRouteImport.update({
    id: '/purchase-record-summary',
    path: '/purchase-record-summary',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpenseSubcategoryRoute =
  LayoutExpenseSubcategoryRouteImport.update({
    id: '/expense-subcategory',
    path: '/expense-subcategory',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutExpenseCategoryRoute = LayoutExpenseCategoryRouteImport.update({
  id: '/expense-category',
  path: '/expense-category',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/expense-category': typeof LayoutExpenseCategoryRoute
  '/expense-subcategory': typeof LayoutExpenseSubcategoryRoute
  '/items': typeof LayoutItemsRoute
  '/purchase-record-summary': typeof LayoutPurchaseRecordSummaryRoute
  '/recycle-bin': typeof LayoutRecycleBinRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/expense-category': typeof LayoutExpenseCategoryRoute
  '/expense-subcategory': typeof LayoutExpenseSubcategoryRoute
  '/items': typeof LayoutItemsRoute
  '/purchase-record-summary': typeof LayoutPurchaseRecordSummaryRoute
  '/recycle-bin': typeof LayoutRecycleBinRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/expense-category': typeof LayoutExpenseCategoryRoute
  '/_layout/expense-subcategory': typeof LayoutExpenseSubcategoryRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/purchase-record-summary': typeof LayoutPurchaseRecordSummaryRoute
  '/_layout/recycle-bin': typeof LayoutRecycleBinRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/expense-category'
    | '/expense-subcategory'
    | '/items'
    | '/purchase-record-summary'
    | '/recycle-bin'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/expense-category'
    | '/expense-subcategory'
    | '/items'
    | '/purchase-record-summary'
    | '/recycle-bin'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/expense-category'
    | '/_layout/expense-subcategory'
    | '/_layout/items'
    | '/_layout/purchase-record-summary'
    | '/_layout/recycle-bin'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recycle-bin': {
      id: '/_layout/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/recycle-bin'
      preLoaderRoute: typeof LayoutRecycleBinRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/purchase-record-summary': {
      id: '/_layout/purchase-record-summary'
      path: '/purchase-record-summary'
      fullPath: '/purchase-record-summary'
      preLoaderRoute: typeof LayoutPurchaseRecordSummaryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expense-subcategory': {
      id: '/_layout/expense-subcategory'
      path: '/expense-subcategory'
      fullPath: '/expense-subcategory'
      preLoaderRoute: typeof LayoutExpenseSubcategoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expense-category': {
      id: '/_layout/expense-category'
      path: '/expense-category'
      fullPath: '/expense-category'
      preLoaderRoute: typeof LayoutExpenseCategoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExpenseCategoryRoute: typeof LayoutExpenseCategoryRoute
  LayoutExpenseSubcategoryRoute: typeof LayoutExpenseSubcategoryRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutPurchaseRecordSummaryRoute: typeof LayoutPurchaseRecordSummaryRoute
  LayoutRecycleBinRoute: typeof LayoutRecycleBinRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExpenseCategoryRoute: LayoutExpenseCategoryRoute,
  LayoutExpenseSubcategoryRoute: LayoutExpenseSubcategoryRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutPurchaseRecordSummaryRoute: LayoutPurchaseRecordSummaryRoute,
  LayoutRecycleBinRoute: LayoutRecycleBinRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
